[package]
name        = "linker_diamondfire"
version     = "0.1.0"
authors     = [ "Totobird Creations <https://github.com/Totobird-Creations>" ]
description = "Linker and CCAPI integration for the Diamondfire block language compiler target"

edition = "2024"

[package.metadata.rust-analyzer]
rustc_private = true


[lints.rust]
unused_parens = "allow"


[dependencies.bridgecg_diamondfire]
path = "../bridgecg_diamondfire"
